scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['$PROMETHEUS_IP:9090']
  - job_name: 'myapp'
    scheme: 'http'
    static_configs:
      - targets: ['192.168.1.226:9568']
